export const mockData = [
  {
    id: 1,
    title: "Asus ROG Strix GeForce RTX 3080 10GB GDDR6X Graphics Card",
    description: {
      one: "2nd Generation RT Cores, 3rd Generation Tensor Cores",
      two: "Axial-tech Fan Design, 2.9-slot design",
      three: "Super Alloy Power II, GPU Tweak II",
      four: "PCI Express 4.0, OpenGL 4.6, CUDA Core: 8704",
    },
    price: 156000,
    brand: "ASUS",
    type: "Graphics Card",
    status: "In Stock",
    imgPath: "/images/rog-strix-geforce-rtx-3080.jpg",
  },
  {
    id: 2,
    title:
      "Sony ZV-E10 24.2MP 4k Touchscreen Vlogging Digital Camera with 16-50mm Lens",
    description: {
      one: "Large APS-C type (23.5 x 15.6 mm), Exmor CMOS sensor",
      two: "Approx. 24.2 megapixels (Effective)",
      three: "7.5 cm (3.0-type) type TFT Display",
      four: "4K video with oversampling for greater detail",
    },
    price: 80900,
    brand: "SONY",
    type: "Camera",
    status: "Up Comming",
    imgPath: "/images/zv-e10-01-500x500.jpg",
  },
  {
    id: 3,
    title: "MSI MAG B760 TOMAHAWK WIFI DDR5 ATX Motherboard",
    description: {
      one: "Supported CPU: 14th/13th/12th Gen Intel Processors (LGA1700)",
      two: "Supported RAM: 4x DDR5, Max 128GB 7000+(OC)",
      three: "Graphics Output: 1x HDMI, 1x DisplayPort",
      four: "Features: 3x M.2 slot, Intel Wi-Fi 6E, Bluetooth 5.3",
    },
    price: 26500,
    brand: "MSI",
    type: "Motherboard",
    status: "In Stock",
    imgPath: "/images/mag-b760-tomahawk.jpg",
  },
  {
    id: 4,
    title: "Intel 12th Gen Core i5-12600K Alder Lake Processor",
    description: {
      one: "Base Clock: P-Core: 3.7 GHz, E-Core: 2.8 GHz",
      two: "Max. Boost: P-Core: 4.9 GHz, E-Core: 3.6 GHz",
      three: "Cache: 20MB, Socket: LGA 1700",
      four: "CPU Cores: 10, CPU Threads: 16",
    },
    price: 29500,
    brand: "INTEL",
    type: "Processor",
    status: "In Stock",
    imgPath: "/images/i5-12600k.jpg",
  },
  {
    id: 5,
    title: 'ASUS TUF Gaming VG279Q3A 27" IPS 180HZ FHD 1ms Gaming Monitor',
    description: {
      one: "Resolution: FHD (1920 x 1080)",
      two: "Display: IPS, 180Hz, 1 ms (GTG)",
      three: "Ports: 1x DisplayPort 1.2, 2x HDMI, Earphone Jack",
      four: "Features: Built-in Speakers, Adaptive-Sync, G-SYNC",
    },
    price: 34500,
    brand: "ASUS",
    type: "Monitor",
    status: "In Stock",
    imgPath: "/images/tuf-gaming-vg279q3a.jpg",
  },
  {
    id: 6,
    title: 'MSI PRO MP273QP 27" 75Hz 1ms IPS WQHD Monitor',
    description: {
      one: "Resolution: WQHD (2560 x 1440)",
      two: "Display: IPS, 75Hz, 1ms (MPRT) / 4ms (GTG)",
      three: "Ports: 2x HDMI, 1x DisplayPort, 1x Headphone-out",
      four: "Features: AMD FreeSync, Anti-Flicker, Less Blue Light",
    },
    price: 35800,
    brand: "MSI",
    type: "Monitor",
    status: "In Stock",
    imgPath: "/images/pro-mp273qp.jpg",
  },
  {
    id: 7,
    title:
      "CANON EOS 200D II 24.1 MP Full HD Wi-Fi DSLR Camera With 18-55MM IS STM Lens",
    description: {
      one: "Dual Pixel CMOS AF",
      two: "24.1MP APS-C CMOS Sensor",
      three: "3,975 selectable focus positions",
      four: "Creative Assist, Creative Filters and Smooth Skin",
    },
    price: 78600,
    brand: "CANON",
    type: "Camera",
    status: "In Stock",
    imgPath: "/images/200d-ii-500x500.jpg",
  },
  {
    id: 8,
    title:
      "ASUS KO NVIDIA GeForce RTX 3060 Ti OC Edition 8GB GDDR6 Graphics Card",
    description: {
      one: "NVIDIA Ampere Streaming Multiprocessors",
      two: "2nd Generation RT Cores",
      three: "Auto-Extreme Technology",
      four: "3rd Generation Tensor Cores",
    },
    price: 39500,
    brand: "ASUS",
    type: "Graphics Card",
    status: "Up Comming",
    imgPath: "/images/ko-rtx-3060-ti-oc-edition.jpg",
  },
  {
    id: 9,
    title: "APOLLO 1120F 1200VA Offline UPS",
    description: {
      one: "Load Capacity: 1200VA",
      two: "Transfer Time: 2ms typical; 5ms maximum",
      three: "Waveform: PWM Simulated Sine wave",
      four: "2 x Lead-Acid maintenance-free battery",
    },
    price: 6400,
    brand: "APOLLO",
    type: "Ups",
    status: "In Stock",
    imgPath: "/images/1120f-01-500x500.jpg",
  },
  {
    id: 10,
    title: "Power Guard 650VA CS Offline UPS (Plastic Body)",
    description: {
      one: "Output Voltage (V): 220/230 VAC +/-10%",
      two: "Frequency (Hz - KHz): 50/60Hz +/-5%",
      three: "Input Voltage (V): 145-280V",
      four: "Load Capacity: 390W",
    },
    price: 3400,
    brand: "POWER GUARD",
    type: "Ups",
    status: "Up Comming",
    imgPath: "/images/Offline-ups-cs-001-500x500.jpg",
  },
];
